### ISSUE TITLE
update front page text (historify the information)

### ISSUE THREAD

**Issue by choisteph** [epibayes/epibayes.github.io#117]
https://covidmapping.org/index.html
branch: [historify-front](https://github.com/epibayes/epibayes.github.io/tree/historify-front)
branch deploy: [historify-front](https://historify-front.onrender.com/)

- double-check preamble (check [branch deploy](https://historify-front.onrender.com/) for current wording)
- re-word and update COVID numbers section
- update what we learned section

**Comment by choisteph** [comment]
check branch [historify-front](https://github.com/epibayes/epibayes.github.io/tree/historify-front).

**Comment by choisteph** [comment]
[(live preview here)](https://historify-front.onrender.com/)

**Comment by choisteph** [comment]
@jzelner : please reword and update "where we got these numbers" and "what we learned" sections

**Comment by jzelner** [comment]
Data Source

The data presented here come from the the Michigan Disease Surveillance System (MDSS) maintained by the Michigan Department of Health and Human Services and reflect counts of PCR-confirmed as well as those determined to be probable  COVID-19 cases in Michigan during the period from March 2020-July 2022. These data were compiled by local health departments and healthcare systems and aggregated, anonymized data were then obtained from MDSS for the purposes of creating these maps.

**Comment by jzelner** [comment]
We can change "What can we learn from mapping COVID-19?" to "What have we learned from mapping COVID-19 incidence in Michigan?"

Curious if @r-setti has thoughts about how we should re-frame this section?

**Comment by choisteph** [comment]
Made above changes. check [this commit](https://github.com/epibayes/epibayes.github.io/commit/6d81ab69fb45081aabc77fe716c3728189e4e99f), see front page updates live [on the deploy here](https://historify-front.onrender.com/).

**Comment by choisteph** [comment]
@emilyandrus if you could see what we have on the front page ([the one at this link](https://historify-front.onrender.com/)) and could help re-frame the "what have we learned from mapping covid-19 incidence in michigan" section to capture the overarching overview/trajectories of covid incidence, that would be highly appreciated! you can feel free to comment here with suggestions, or push text updates directly to the historify-front branch.
